receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    logs_index: "logs"
    traces_index: "traces"
    metrics_index: "metrics"
    create_index_templates: true
    

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch] 