receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1000
  resource:
    attributes:
      - key: monitoring.system
        value: otel-api-monitoring
        action: upsert

exporters:
  elasticsearch:
    endpoints: [http://elasticsearch:9200]
    traces_index: traces-otel
    logs_index: logs-otel  # Add a logs index for Elasticsearch

  logging:
    loglevel: debug
    
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [elasticsearch, logging]

    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [prometheus, logging]

    logs:  # Add a logs pipeline
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [elasticsearch, logging]
  
  telemetry:
    logs:
      level: "debug"