global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'

  # - job_name: 'api-services'
  #   static_configs:
  #     - targets: 
  #         - 'payment-api:8000'
  #         - 'order-api:8000'
  #         - 'inventory-api:8000'
  #         - 'user-api:8000'
  #   metrics_path: '/metrics' 