receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp:
    endpoint: "http://localhost:4318"  # APM Server OTLP HTTP endpoint

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [otlp]
