receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  # Add resource processor to ensure service name is properly propagated
  resource:
    attributes:
      - key: service.name
        action: keep
      - key: service.version
        action: keep
      - key: deployment.environment
        action: keep

exporters:
  # Simplified Elasticsearch exporter configuration for traces
  elasticsearch/traces:
    endpoints:
      - "http://elasticsearch:9200"
    traces_index: "traces-bank"
    # Set very conservative timeout values
    timeout: 120s
    tls:
      insecure: true
  
  # Simplified Elasticsearch exporter configuration for logs
  elasticsearch/logs:
    endpoints:
      - "http://elasticsearch:9200"
    logs_index: "banking-logs"
    # Set very conservative timeout values
    timeout: 120s
    tls:
      insecure: true
  
  # Prometheus exporter for metrics
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: bank_api
  
  # Debug exporter with more verbose options
  logging:
    verbosity: detailed
    sampling_initial: 1
    sampling_thereafter: 1

service:
  # Enable telemetry collection for the collector itself
  telemetry:
    logs:
      level: debug
      development: true
      encoding: console

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [elasticsearch/traces, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging]
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [elasticsearch/logs, logging] 