receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  # Add metric name/description as fields
  metricstransform:
    transforms:
      - include: .*
        match_type: regexp
        action: update
        operations:
          - action: add_label
            new_label: metric_name
            new_value: $1

exporters:
  # Elasticsearch exporter for logs and traces
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    index: "api-monitoring"
  
  # Prometheus exporter for metrics
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: dice_roll_app
    const_labels:
      service: "dice-roll-app"
      environment: "development"
  
  # Debug exporter
  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging] # Export metrics to Prometheus
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch, logging] 