receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  # Add resource processor to ensure service name is properly propagated
  resource:
    attributes:
      - key: service.name
        action: upsert
        value: "bank-api"

exporters:
  # Elasticsearch exporter - separate configuration for logs and traces
  elasticsearch/traces:
    endpoints: ["http://elasticsearch:9200"]
    traces_index: "traces-bank"
  
  elasticsearch/logs:
    endpoints: ["http://elasticsearch:9200"]
    logs_index: "banking-logs"
  
  # Prometheus exporter for metrics
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: bank_api
  
  # Debug exporter
  logging:
    verbosity: detailed
    sampling_initial: 1
    sampling_thereafter: 1

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [elasticsearch/traces, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch/logs, logging] 