receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  elasticsearch:
    endpoints: ["https://elasticsearch:9200"]
    username: ${env:ELASTICSEARCH_USERNAME}
    password: ${env:ELASTICSEARCH_PASSWORD}
    index: "api-monitoring-%{service.name}-%{telemetry.sdk.language}-%{Y.MM.dd}"
    mapping:
      enabled: true
    logs_index: "api-monitoring-logs-%{service.name}-%{Y.MM.dd}"
    metrics_index: "api-monitoring-metrics-%{service.name}-%{Y.MM.dd}"
    traces_index: "api-monitoring-traces-%{service.name}-%{Y.MM.dd}"
    tls:
      insecure: true  # For development only, set to false in production
  
  # Adding logging exporter for debugging
  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch, logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch, logging] 