receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  # Add metric name/description as fields
  metricstransform:
    transforms:
      - include: .*
        match_type: regexp
        action: update
        operations:
          - action: add_label
            new_label: metric_name
            new_value: $1

exporters:
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    index: "api-monitoring"
    tls:
      insecure: true  # For development only, set to false in production
  
  # Specific index for metrics
  elasticsearch/metrics:
    endpoints: ["http://elasticsearch:9200"]
    index: "api-monitoring-metrics"
    tls:
      insecure: true  # For development only, set to false in production
  
  # Adding logging exporter for debugging
  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch, logging]
    metrics:
      receivers: [otlp]
      processors: [batch, metricstransform]
      exporters: [elasticsearch/metrics, logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch, logging] 